services:
  stats-server:
    build: ./stat_svc/stats-server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
  ewm-service:
    build: ./ewm-service
    image: ewm-service_image
    container_name: ewm-service_name
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - CLIENT_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm

  stats-db:
    image: postgres:16.1
    container_name: db-container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=vlad
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
  ewm-db:
    image: postgres:14-alpine
    container_name: postgres-ewm-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=vlad
      - POSTGRES_PASSWORD=12345
