services:
  stat_svc_server:
    build: stats-server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - db
  ewm-service:
    build: ewm-service
    image: ewm-service_image
    container_name: ewm-service_name
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/explore-with-me
      - SPRING_DATASOURCE_USERNAME=vlad
      - SPRING_DATASOURCE_PASSWORD=12345

  db:
    image: postgres:16.1
    container_name: db-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=vlad
      - POSTGRES_DB=stats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
