services:
  stats-server:
    build: ./stat_svc/stats-server
    image: stats-server-image
    container_name: stats-server-image
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SERVER_PORT=9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explore-with-me
      - SPRING_DATASOURCE_USER=vlad
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_DATASOURCE_DRIVER=org.postgresql.Driver
      - SPRING_SQL_INIT_MODE=always
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
  stats-db:
    image: postgres:16.1
    container_name: db-container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=explore-with-me
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=vlad
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
  ewm-service:
    build: ewm-service
    image: ewm-service_image
    container_name: ewm-service_name
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - CLIENT_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/explore-with-me
      - SPRING_DATASOURCE_USER=vlad
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_DATASOURCE_DRIVER=org.postgresql.Driver
      - SPRING_SQL_INIT_MODE=always
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
  ewm-db:
    image: postgres:14-alpine
    container_name: postgres-ewm-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explore-with-me
      - POSTGRES_USER=vlad
      - POSTGRES_PASSWORD=12345
