services:
  stat_svc_server:
    build: ./stat_svc/stat_svc_server
    image: stat_svc_server
    container_name: stat_svc_server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - STAT_SVC_SERVER=http://server:9090
  ewm-service:
    build: ./ewm-server
    image: ewm-server
    container_name: ewm-server
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/explore-with-me
      - SPRING_DATASOURCE_USERNAME=vlad
      - SPRING_DATASOURCE_PASSWORD=12345

  db:
    image: postgres:16.1
    container_name: explore-with-me
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=vlad
      - POSTGRES_DB=stats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
